apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'controller'
        static_configs:
          - targets: ['controller-service.myapp-namespace.svc.cluster.local:5000']

      - job_name: 'validator'
        static_configs:
          - targets: ['validator-service.myapp-namespace.svc.cluster.local:5000']

      - job_name: 'microservicio_core'
        static_configs:
          - targets: ['microservicio-core-service.myapp-namespace.svc.cluster.local:5000']
