apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: myapp-namespace
spec:
  selector:
    app: controller
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30081
  type: NodePort
