apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: myapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: controller:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
