apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app
  namespace: myapp-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: mi-app
        image: miapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000