apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
  namespace: myapp-namespace
spec:
  selector:
    app: mi-app
  type: NodePort
  ports:
    - port: 5000        # puerto interno del contenedor
      targetPort: 5000  # puerto Flask
      nodePort: 30080   # puerto del host (localhost:30080)
