apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
  namespace: myapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      containers:
      - name: validator
        image: validator:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
